services:
  jemehotelsproject:
    build:
      context: .
      dockerfile: JemeHotelsProject/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ConnectionStrings__JemeHotelsConnectionString=Server=db;Database=JemeHotelsDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__JemeHotelsAuthConnectionString=Server=db;Database=JemeHotelsAuthDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1434:1433"
    volumes:
      - mssql-data:/var/opt/mssql
  
volumes:
  mssql-data:

