// <auto-generated />
using System;
using JemeHotelsProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JemeHotelsProject.Migrations
{
    [DbContext(typeof(JemeHotelsDbContext))]
    partial class JemeHotelsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JemeHotelsProject.Models.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("numberOfDays")
                        .HasColumnType("int");

                    b.Property<decimal>("totalBill")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("JemeHotelsProject.Models.Domain.Guest", b =>
                {
                    b.Property<Guid>("GuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuestID");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            GuestID = new Guid("bedc78e9-661d-469c-b504-cecdfd9f8a4c"),
                            Name = "Dr. Obasi",
                            PhoneNo = "08056245835"
                        },
                        new
                        {
                            GuestID = new Guid("39d9d260-25e3-4e33-930b-eb18547dc1b3"),
                            Name = "Ossai",
                            PhoneNo = "08079885512"
                        });
                });

            modelBuilder.Entity("JemeHotelsProject.Models.Domain.Room", b =>
                {
                    b.Property<Guid>("roomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("roomNumber")
                        .HasColumnType("int");

                    b.Property<string>("roomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roomID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("JemeHotelsProject.Models.Domain.Booking", b =>
                {
                    b.HasOne("JemeHotelsProject.Models.Domain.Guest", "Guests")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JemeHotelsProject.Models.Domain.Room", "Rooms")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guests");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
